server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://eureka:password@discovery-server:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spring-boot-microservices-realm