spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true


server:
  port: 8072


#  security:
#    oauth2:
#      resource-server:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm



#logging:
#  level:
#    root: info
#    org:
#      springframework:
#        cloud:
#          gateway: trace

#management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/zipkin
#  tracing:
#    sampling:
#      probability: 1.0