spring:
  application:
    name: config-server
  profiles:
    active: git


  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/TimofeyTrofimovich/config.git
          search-paths:
            - "{application}/{profile}"
          password: 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
          username: "TimofeyTrofimovich"
          clone-on-start: true
        encrypt:
          enabled: true

encrypt:
  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
